project_id = "yvfreghenveswocfphbs"

[functions.import-products]
verify_jwt = false

[functions.calculate-shipping]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.owner-efi-charge]
verify_jwt = false

[functions.webhook-efi]
verify_jwt = false

[functions.check-subscription-expiry]
verify_jwt = false
